export const FORMATIONS = [
  {
    id: 1,
    author_id: 1,
    title: "Test Formation",
    description: "This is a test formation",
    video: "https://example.com/test-video",
    category_id: 1,
    difficulty: "easy",
    completionTime: "2023-01-01T00:00:00.000Z",
    qualityRating: 5,
    coverImage: "https://example.com/test-image",
  },
  {
    id: 2,
    author_id: 1,
    title: "Test2",
    description: "This is a test ",
    video: "https://assets/test-video",
    category_id: 1,
    difficulty: "easy",
    completionTime: "2023-01-01T00:00:00.000Z",
    qualityRating: 5,
    coverImage: "https://assets/test-image",
  },
  {
    id: 3,
    author_id: 1,
    title: "Test3",
    description: "This is a test formation",
    video: "https://example.com/test-video",
    category_id: 1,
    difficulty: "easy",
    completionTime: "2023-01-01T00:00:00.000Z",
    qualityRating: 5,
    coverImage: "https://example.com/test-image",
  },
  {
    id: 4,
    author_id: 1,
    title: "Test4",
    description: "This is a test formation",
    video: "https://example.com/test-video",
    category_id: 1,
    difficulty: "easy",
    completionTime: "2023-01-01T00:00:00.000Z",
    qualityRating: 5,
    coverImage: "https://example.com/test-image",
  },
  {
    id: 5,
    author_id: 1,
    title: "Test5",
    description: "This is a test formation",
    video: "https://example.com/test-video",
    category_id: 1,
    difficulty: "easy",
    completionTime: "2023-01-01T00:00:00.000Z",
    qualityRating: 5,
    coverImage: "https://example.com/test-image",
  },
];
