export const API_URL = "https://virtual-sentinel-5db263dece23.herokuapp.com";

export const FORMATIONS = [
  {
    id: 1,
    author: "Gana Fall",
    title: "Test Formation",
    description: "This is a test formation",
    video: "https://example.com/test-video",
    category: "Fondamentaux de la cybersecurite",
    difficulty: "easy",
    completionTime: "2023-01-01T00:00:00.000Z",
    qualityRating: 5,
    coverImage: require("../assets/images/mock1.jpg"),
  },
  {
    id: 2,
    author: "Gana Fall",
    title: "Test2",
    description: "This is a test ",
    video: "https://assets/test-video",
    category: "Fondamentaux de la cybersecurite",
    difficulty: "easy",
    completionTime: "2023-01-01T00:00:00.000Z",
    qualityRating: 5,
    coverImage: require("../assets/images/mock2.png"),
  },
  {
    id: 3,
    author: "Gana Fall",
    title: "Test3",
    description: "This is a test formation",
    video: "https://example.com/test-video",
    category: "Fondamentaux de la cybersecurite",
    difficulty: "easy",
    completionTime: "2023-01-01T00:00:00.000Z",
    qualityRating: 5,
    coverImage: require("../assets/images/mock3.jpg"),
  },
  {
    id: 4,
    author: "Gana Fall",
    title: "Test4",
    description: "This is a test formation",
    video: "https://example.com/test-video",
    category: "Fondamentaux de la cybersecurite",
    difficulty: "easy",
    completionTime: "2023-01-01T00:00:00.000Z",
    qualityRating: 5,
    coverImage: require("../assets/images/mock3.jpg"),
  },
  {
    id: 5,
    author: "Gana Fall",
    title: "Test5",
    description: "This is a test formation",
    video: "https://example.com/test-video",
    category: "Fondamentaux de la cybersecurite",
    difficulty: "easy",
    completionTime: "2023-01-01T00:00:00.000Z",
    qualityRating: 5,
    coverImage: require("../assets/images/mock1.jpg"),
  },
];
